const mutationTypes = {
    SET_LOGIN_USERINFO: 'SET_LOGIN_USERINFO',
    SET_IS_MANAGER: 'SET_IS_MANAGER',
    SET_CURRENT_NAVI: 'SET_CURRENT_NAVI',
    SET_CURRENT_SUBNAVI: 'SET_CURRENT_SUBNAVI',
    SET_HEADERMODE: 'SET_HEADERMODE',
    SET_DATALIST_DEFAULTTAB: 'SET_DATALIST_DEFAULTTAB',
    SET_SPIN_STATUS: 'SET_SPIN_STATUS',
}

export default mutationTypes